# Generated by Django 5.0.1 on 2024-01-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='actas_bd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eecc', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=100)),
                ('oc', models.IntegerField()),
                ('ip_hijo', models.CharField(max_length=100)),
                ('total_OC', models.FloatField()),
                ('total_certificar', models.FloatField()),
                ('termino_obra', models.DateField()),
                ('servicio_obra', models.DateField()),
                ('posiciones', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='bd_actas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='clean_actas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='csv_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='actas_lps/csv_files/')),
            ],
        ),
    ]
