# Generated by Django 5.0.1 on 2024-01-22 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas_lps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bd_actas',
        ),
    ]
