# Generated by Django 5.0.1 on 2024-02-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actas_lps', '0004_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actas_bd',
            name='posiciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
