# Generated by Django 5.0.1 on 2024-02-08 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas_lps', '0005_alter_actas_bd_posiciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actas_bd',
            old_name='project',
            new_name='proyecto',
        ),
    ]
