# Generated by Django 5.0.1 on 2024-02-08 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actas_lps', '0006_rename_project_actas_bd_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actas_bd',
            old_name='eecc',
            new_name='EECC',
        ),
        migrations.RenameField(
            model_name='actas_bd',
            old_name='ip_hijo',
            new_name='IP_Hijo',
        ),
        migrations.RenameField(
            model_name='actas_bd',
            old_name='oc',
            new_name='OC',
        ),
        migrations.RenameField(
            model_name='actas_bd',
            old_name='proyecto',
            new_name='Proyecto',
        ),
    ]
